/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        background: '#131318',
        'on-background': '#e4e1e9',
        surface: '#18181f',
        'on-surface': '#e4e1e9',
        'surface-variant': '#2b2931',
        'on-surface-variant': '#918f9d',
        'surface-container-lowest': '#0d0d12',
        'surface-container-low': '#18181f',
        'surface-container': '#1f1f25',
        'surface-container-high': '#292931',
        'surface-container-highest': '#34343d',
        primary: '#e9c349',
        'on-primary': '#3a2f00',
        secondary: '#cfc4a6',
        'on-secondary': '#363018',
        tertiary: '#aab6a2',
        'on-tertiary': '#182315',
        error: '#ffb4ab',
        'on-error': '#690005',
        outline: '#918f9d',
        'outline-variant': '#47454f',
        'inverse-surface': '#e4e1e9',
        'inverse-on-surface': '#18181f',
        'inverse-primary': '#715c00',
      },
      fontFamily: {
        sans: ['"Matter"', 'system-ui', 'sans-serif'],
        serif: ['"Noto Serif"', 'serif'],
        display: ['"Melodrama"', 'serif'],
        body: ['"Manrope"', 'system-ui', 'sans-serif'],
        headline: ['"Noto Serif"', 'serif'],
        label: ['"Manrope"', 'system-ui', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
